package com.softala.sr2.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReservedItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservedItemAllPropertiesEquals(ReservedItem expected, ReservedItem actual) {
        assertReservedItemAutoGeneratedPropertiesEquals(expected, actual);
        assertReservedItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservedItemAllUpdatablePropertiesEquals(ReservedItem expected, ReservedItem actual) {
        assertReservedItemUpdatableFieldsEquals(expected, actual);
        assertReservedItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservedItemAutoGeneratedPropertiesEquals(ReservedItem expected, ReservedItem actual) {
        assertThat(expected)
            .as("Verify ReservedItem auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservedItemUpdatableFieldsEquals(ReservedItem expected, ReservedItem actual) {
        assertThat(expected)
            .as("Verify ReservedItem relevant properties")
            .satisfies(e -> assertThat(e.getQuantity()).as("check quantity").isEqualTo(actual.getQuantity()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservedItemUpdatableRelationshipsEquals(ReservedItem expected, ReservedItem actual) {
        assertThat(expected)
            .as("Verify ReservedItem relationships")
            .satisfies(e -> assertThat(e.getReservation()).as("check reservation").isEqualTo(actual.getReservation()))
            .satisfies(e -> assertThat(e.getStockItem()).as("check stockItem").isEqualTo(actual.getStockItem()));
    }
}
