package com.softala.sr2.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StockItemTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockItemTypeAllPropertiesEquals(StockItemType expected, StockItemType actual) {
        assertStockItemTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertStockItemTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockItemTypeAllUpdatablePropertiesEquals(StockItemType expected, StockItemType actual) {
        assertStockItemTypeUpdatableFieldsEquals(expected, actual);
        assertStockItemTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockItemTypeAutoGeneratedPropertiesEquals(StockItemType expected, StockItemType actual) {
        assertThat(expected)
            .as("Verify StockItemType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockItemTypeUpdatableFieldsEquals(StockItemType expected, StockItemType actual) {
        assertThat(expected)
            .as("Verify StockItemType relevant properties")
            .satisfies(e -> assertThat(e.getTypeName()).as("check typeName").isEqualTo(actual.getTypeName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockItemTypeUpdatableRelationshipsEquals(StockItemType expected, StockItemType actual) {}
}
